//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hehimtap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cloud
    {
        public int Id { get; set; }
        public int XeberId { get; set; }
        public int TeqId { get; set; }
    
        public virtual News News { get; set; }
        public virtual Teq Teq { get; set; }
    }
}
