//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hehimtap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Basliq { get; set; }
        public string Metn { get; set; }
        public System.DateTime Tarix { get; set; }
        public bool Status { get; set; }
        public int Ulduzsayi { get; set; }
        public int DoctorsId { get; set; }
        public int UsersId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
