//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hehimtap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HekimTapEntities : DbContext
    {
        public HekimTapEntities()
            : base("name=HekimTapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Beyanat> Beyanats { get; set; }
        public virtual DbSet<Cloud> Clouds { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<DoctorCategory> DoctorCategories { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsCategory> NewsCategories { get; set; }
        public virtual DbSet<Personel> Personels { get; set; }
        public virtual DbSet<PersonelCategory> PersonelCategories { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Rezerv> Rezervs { get; set; }
        public virtual DbSet<Teq> Teqs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Ziyaret> Ziyarets { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
    }
}
